import { chromium } from "playwright";
import fs from "fs";
import path from "path";

const {
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID,
  CHECK_INTERVAL_SECONDS = "10",
  DATA_DIR = "/data",
  VINTED_SEARCH_URL =
    "https://www.vinted.co.uk/catalog?search_text=drakes&time=1751320018&brand_ids[]=389025&page=1"
} = process.env;

if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
  console.error("❌ Missing Telegram environment variables.");
  process.exit(1);
}

fs.mkdirSync(DATA_DIR, { recursive: true });

const SEEN_FILE = path.join(
  DATA_DIR,
  "vinted_drakes_seen.json"
);

function sleep(ms) {
  return new Promise(resolve =>
    setTimeout(resolve, ms)
  );
}

function loadSeen() {
  try {
    return new Set(
      JSON.parse(
        fs.readFileSync(SEEN_FILE, "utf8")
      )
    );
  } catch {
    return new Set();
  }
}

function saveSeen(seen) {
  try {
    fs.writeFileSync(
      SEEN_FILE,
      JSON.stringify([...seen], null, 2)
    );
  } catch (error) {
    console.error(
      "Could not save seen items:",
      error.message
    );
  }
}

function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function getPhoto(item) {
  return (
    item.photo?.url ||
    item.photo?.full_size_url ||
    item.photos?.[0]?.url ||
    item.photos?.[0]?.full_size_url ||
    ""
  );
}

async function telegramRequest(method, body) {
  const response = await fetch(
    `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/${method}`,
    {
      method: "POST",

      headers: {
        "Content-Type": "application/json"
      },

      body: JSON.stringify(body)
    }
  );

  const data = await response.json();

  if (!data.ok) {
    throw new Error(
      `Telegram ${data.error_code}: ${data.description}`
    );
  }
}

async function sendTelegram(item) {
  const relativeUrl =
    item.url ||
    `/items/${item.id}`;

  const itemUrl =
    relativeUrl.startsWith("http")
      ? relativeUrl
      : `https://www.vinted.co.uk${relativeUrl}`;

  const price =
    item.price?.amount
      ? `£${item.price.amount}`
      : "";

  const totalPrice =
    item.total_item_price?.amount
      ? `£${item.total_item_price.amount}`
      : "";

  const seller =
    item.user?.login || "";

  const message = [
    "🚨 <b>NEW DRAKE'S LISTING</b>",
    "",
    `<b>${escapeHtml(
      item.title || "New Drake's listing"
    )}</b>`,
    "",
    price
      ? `💷 <b>Price:</b> ${escapeHtml(price)}`
      : "",
    totalPrice &&
    totalPrice !== price
      ? `🛍 <b>Incl. buyer protection:</b> ${escapeHtml(totalPrice)}`
      : "",
    seller
      ? `👤 <b>Seller:</b> ${escapeHtml(seller)}`
      : "",
    "",
    `<a href="${itemUrl}">OPEN ON VINTED</a>`
  ]
    .filter(Boolean)
    .join("\n");

  const photo = getPhoto(item);

  if (photo) {
    try {
      await telegramRequest(
        "sendPhoto",
        {
          chat_id:
            TELEGRAM_CHAT_ID,

          photo,

          caption:
            message,

          parse_mode:
            "HTML"
        }
      );

      return;

    } catch (error) {
      console.log(
        "Photo send failed, using text:",
        error.message
      );
    }
  }

  await telegramRequest(
    "sendMessage",
    {
      chat_id:
        TELEGRAM_CHAT_ID,

      text:
        message,

      parse_mode:
        "HTML",

      disable_web_page_preview:
        false
    }
  );
}

async function main() {
  const seen =
    loadSeen();

  console.log(
    `Loaded ${seen.size} previously seen item(s).`
  );

  console.log(
    "🚀 Starting Vinted page-refresh monitor."
  );

  console.log(
    `Search URL: ${VINTED_SEARCH_URL}`
  );

  console.log(
    `Checking every ${CHECK_INTERVAL_SECONDS} seconds.`
  );

  const browser =
    await chromium.launch({
      headless: true,

      args: [
        "--no-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu"
      ]
    });

  const context =
    await browser.newContext({
      locale:
        "en-GB",

      timezoneId:
        "Europe/London",

      userAgent:
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 " +
        "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",

      extraHTTPHeaders: {
        "Accept-Language":
          "en-GB,en;q=0.9"
      }
    });

  const page =
    await context.newPage();

  let latestCatalogue = null;
  let captureNumber = 0;

  /*
   * Listen continuously for the SAME catalogue
   * response generated by the actual Vinted page.
   */
  page.on(
    "response",
    async response => {
      try {
        const url =
          response.url();

        const isCatalogue =
          url.includes(
            "/svc-catalogue/items"
          ) ||
          url.includes(
            "/api/v2/catalog/items"
          );

        if (!isCatalogue) {
          return;
        }

        console.log(
          `🔎 Page catalogue response: ${response.status()}`
        );

        console.log(
          url
        );

        if (
          response.status() !== 200
        ) {
          return;
        }

        const data =
          await response.json();

        if (
          !Array.isArray(
            data.items
          )
        ) {
          return;
        }

        latestCatalogue =
          data.items;

        captureNumber++;

        console.log(
          `✅ Captured ${data.items.length} item(s) from Vinted page.`
        );

      } catch (error) {
        console.log(
          "Catalogue capture warning:",
          error.message
        );
      }
    }
  );

  /*
   * Establish UK Vinted session first.
   */
  console.log(
    "Opening Vinted UK..."
  );

  await page.goto(
    "https://www.vinted.co.uk/",
    {
      waitUntil:
        "domcontentloaded",

      timeout:
        60000
    }
  );

  await page.waitForTimeout(
    2500
  );

  console.log(
    "✅ UK Vinted session ready."
  );

  let baselineDone =
    seen.size > 0;

  let errors = 0;

  while (true) {
    const checkStarted =
      Date.now();

    try {
      console.log(
        "🔄 Refreshing your Drake's search..."
      );

      latestCatalogue =
        null;

      const captureBefore =
        captureNumber;

      /*
       * THIS IS THE IMPORTANT PART:
       *
       * We open the exact search page supplied
       * by you instead of building our own API
       * search.
       */
      await page.goto(
        VINTED_SEARCH_URL,
        {
          waitUntil:
            "domcontentloaded",

          timeout:
            60000
        }
      );

      /*
       * Wait for the page itself to make its
       * catalogue request.
       */
      const waitStarted =
        Date.now();

      while (
        captureNumber ===
          captureBefore &&
        Date.now() - waitStarted <
          20000
      ) {
        await sleep(250);
      }

      if (
        captureNumber ===
          captureBefore ||
        !Array.isArray(
          latestCatalogue
        )
      ) {
        throw new Error(
          "Vinted page loaded but no catalogue response was captured."
        );
      }

      const items =
        latestCatalogue.filter(
          item =>
            item &&
            item.id
        );

      console.log(
        `Page returned ${items.length} listing(s).`
      );

      /*
       * First successful result becomes baseline.
       */
      if (!baselineDone) {
        for (
          const item of items
        ) {
          seen.add(
            String(item.id)
          );
        }

        saveSeen(seen);

        baselineDone =
          true;

        console.log(
          `✅ Baseline saved with ${seen.size} current listing(s).`
        );
      }

      else {
        const newItems =
          items.filter(
            item =>
              !seen.has(
                String(item.id)
              )
          );

        /*
         * Safety lock against another accidental
         * flood of unrelated Vinted listings.
         */
        if (
          newItems.length > 10
        ) {
          console.error(
            `🛑 SAFETY LOCK: ${newItems.length} unseen listings appeared.`
          );

          console.error(
            "Telegram alerts suppressed."
          );
        }

        else if (
          newItems.length === 0
        ) {
          console.log(
            "No new listings."
          );
        }

        else {
          console.log(
            `🚨 ${newItems.length} NEW listing(s)!`
          );

          for (
            const item of
              [...newItems].reverse()
          ) {
            try {
              console.log(
                `🚨 NEW: ${item.title}`
              );

              await sendTelegram(
                item
              );

              seen.add(
                String(item.id)
              );

              saveSeen(
                seen
              );

              console.log(
                `✅ Telegram sent for ${item.id}`
              );

            } catch (error) {
              console.error(
                `Telegram failed for ${item.id}:`,
                error.message
              );
            }
          }
        }
      }

      errors = 0;

    } catch (error) {
      errors++;

      console.error(
        "❌ Vinted check failed:",
        error.message
      );

      if (
        errors >= 3
      ) {
        try {
          console.log(
            "♻️ Re-establishing UK Vinted session..."
          );

          await page.goto(
            "https://www.vinted.co.uk/",
            {
              waitUntil:
                "domcontentloaded",

              timeout:
                60000
            }
          );

          await page.waitForTimeout(
            3000
          );

          errors = 0;

        } catch (
          refreshError
        ) {
          console.error(
            "Session refresh failed:",
            refreshError.message
          );
        }
      }
    }

    /*
     * Aim for the chosen interval measured
     * from the beginning of the check,
     * rather than adding the interval on top
     * of however long the check itself took.
     */
    const elapsed =
      Date.now() -
      checkStarted;

    const target =
      Number(
        CHECK_INTERVAL_SECONDS
      ) * 1000;

    const remaining =
      Math.max(
        1000,
        target - elapsed
      );

    await sleep(
      remaining
    );
  }
}

main().catch(error => {
  console.error(
    "❌ Fatal monitor error:",
    error
  );

  process.exit(1);
});
